### PR TITLE
feat: implement ISG

### PR DESCRIPTION
**Pull request by smakosh**
## What's new?
- move from getServerSideProps to getStaticPaths and getStaticProps

## Suggestions
- You can return an empty ticket as a skeleton loading when fallback is on

### CODE REVIEW

**Comment by smakosh** [comment]
@yjose

**Comment by melbarch** [comment]
Indentation is not homogenous with the code base

**Comment by smakosh** [comment]
> Indentation is not homogenous with the code base

The project doesn't have prettier configured nor Eslint.

**Comment by smakosh** [comment]
> Indentation is not homogenous with the code base

It has been fixed, it was nice using GitHub codespaces

**Pull request closed without merging**
